### ISSUE TITLE
there is no setup.py

### ISSUE THREAD

**Issue by evolgenomology** [dave-the-scientist/patternHmm#1]
Hi!
There is no setup.py contained.

Cheers

P

**Comment by dave-the-scientist** [comment]
Ah, that is true. This package is meant to be installed by downloading the compressed "Release" file, not by cloning or pulling from github. I'll update the readme to reflect that.

**Comment by evolgenomology** [comment]
There is also no setup.py in the zip as far as I can see.


On 16 July 2018 at 18:17:24, Dave (notifications@github.com) wrote:

Ah, that is true. This package is meant to be installed by downloading the
compressed "Release" file, not by cloning or pulling from github. I'll
update the readme to reflect that.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dave-the-scientist/patternHmm/issues/1#issuecomment-405320569>,
or mute the thread

**Comment by dave-the-scientist** [comment]
Apologies for that. I'll look into it.

**Comment by dave-the-scientist** [comment]
It appears the .zip release is not up to date. It will take me some time to correct that, but in the meantime you can use the .tar.gz release. If you're on Windows, the program 7-zip should allow you to unpack it.

EDIT: the .zip file is not actually a version of the release file, but is just a compressed archive of the files in the repo. As such, it is not suitable to install. The release file is the one named "patternHmm-0.4.tar.gz".

**Comment by evolgenomology** [comment]
Thanks mate, but were is the tarball?


On 16 July 2018 at 19:23:16, Dave (notifications@github.com) wrote:

It appears the .zip release is not up to date. It will take me some time to
correct that, but in the meantime you can use the .tar.gz release. If
you're on Windows, the program 7-zip should allow you to unpack it.

EDIT: the .zip file is not actually a version of the release file, but is
just a compressed archive of the files in the repo. As such, it is not
suitable to install. The release file is the one named
"patternHmm-0.4.tar.gz".

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dave-the-scientist/patternHmm/issues/1#issuecomment-405329393>,
or mute the thread

**Comment by dave-the-scientist** [comment]
You can find it on the "Releases" page (https://github.com/dave-the-scientist/patternHmm/releases). On the main patternHmm page you'll see a blue and black bar containing info on commits, branches, releases, and contributors. Click the '1 release' button, and you'll find the page. That's where stable versions of the software can be found (currently v0.4); pulling or cloning the repo will get you the development versions, which may or may not be ready for general use (they are not in this case). Make sure you click the "patternHmm-0.4.tar.gz" link instead of the "Source code (tar.gz)", which would just get you a compressed version of the development version (which won't have a setup.py file).

**Comment by evolgenomology** [comment]
OK, found it. Thanks!


On 16 July 2018 at 22:39:51, Dave (notifications@github.com) wrote:

You can find it on the "Releases" page (
https://github.com/dave-the-scientist/patternHmm/releases). On the main
patternHmm page you'll see a blue and black bar containing info on commits,
branches, releases, and contributors. Click the '1 release' button, and
you'll find the page. That's where stable versions of the software can be
found (currently v0.4); pulling or cloning the repo will get you the
development versions, which may or may not be ready for general use (they
are not in this case). Make sure you click the "patternHmm-0.4.tar.gz" link
instead of the "Source code (tar.gz)", which would just get you a
compressed version of the development version (which won't have a setup.py
file).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dave-the-scientist/patternHmm/issues/1#issuecomment-405390389>,
or mute the thread
